server:
  port: ${SERVER_PORT}
spring:

  datasource:
    driver-class-name: ${DB_CLASS}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  accessSecret: ${ACCESS_SECRET}
  refreshSecret: ${REFRESH_SECRET}
  accessTime: 100000000
  refreshTime: 1209600

cloud:
  aws:
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_BUCKET_NAME}
    stack:
      auto: false
    credentials:
      secret-key: ${AWS_SECRET}
      access-key: ${AWS_ACCESS}